#!/bin/bash
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

REVISION=$(git log --pretty=format:'%h' -n 1)
FILE_LIST=$(git diff --diff-filter=d --cached --name-only | grep -E '\.(js|jsx|ts|tsx|vue)$')
FILE_COUNT=0

if [ ${#FILE_LIST} -gt 0 ]; then
    echo "FILE_LIST NOT EMPTY"
    FILE_COUNT=${#FILE_LIST[@]}
fi

echo $FILE_LIST
echo $FILE_COUNT

FILE_STRING='file'

if [ "$FILE_COUNT" -gt 1 ]; then
    FILE_STRING='files'
fi

ESLINT=common/temp/node_modules/.bin/eslint
PRETTIER=common/temp/node_modules/.bin/pretty-quick

BOLD=`tput bold`
NORMAL=`tput sgr0`

echo --------------------------------------------
echo Starting Git hook: pre-commit
echo --------------------------------------------

echo -e "\nRunning ESLint\n"

if [ -f $ESLINT ]; then
    echo "🔍 Finding changed files since ${BOLD}git${NORMAL} revision ${BOLD}$REVISION${NORMAL}."
    echo "🎯 Found ${BOLD}${FILE_COUNT}${NORMAL} changed $FILE_STRING."

    if [ "$FILE_COUNT" -gt 0 ]; then
        `$ESLINT ${FILE_LIST[*]} "$@" --fix`
    fi

    if [ $? -ne 0 ]; then
        echo "⛔️  Check failed, please fix the above issues before committing."
    else
        echo "✅  Everything is awesome!"
    fi
else
  echo "❌ Error running ESLint: $ESLINT"
fi

echo -e "\nRunning Prettier\n"

if [ -f $PRETTIER ]; then
  $PRETTIER
else
  echo "❌ Error running Prettier: $PRETTIER"
fi

echo --------------------------------------------
echo Finished Git hook: pre-commit
echo --------------------------------------------