const descriptors = [
  "Arctic",
  "Big",
  "Blue",
  "Bronze",
  "Buzzed",
  "Charming",
  "Chill",
  "Chipped",
  "Clever",
  "Copper",
  "Crafty",
  "Crazy",
  "Crooked",
  "Curious",
  "Dancing",
  "Dandy",
  "Dizzy",
  "Drekky",
  "Drunken",
  "Eager",
  "Fat",
  "Fiesty",
  "Flying",
  "Fragged",
  "Fragging",
  "Frozen",
  "Funky",
  "Geeked",
  "Ginger",
  "Golden",
  "Good",
  "Grand",
  "Hazy",
  "Hidden",
  "Howling",
  "Jaded",
  "Jolly",
  "Jumping",
  "Lazy",
  "Leaning",
  "Little",
  "Lucky",
  "Madcap",
  "Magic",
  "Malted",
  "Merry",
  "Mighty",
  "Mystic",
  "Naughty",
  "Original",
  "Painted",
  "Pickled",
  "Pink",
  "Polished",
  "Proud",
  "Purple",
  "Rambling",
  "Rogue",
  "Roke",
  "Rowdy",
  "Royal",
  "Runaway",
  "Rusty",
  "Salty",
  "Secret",
  "Silver",
  "Singing",
  "SINless",
  "Slow",
  "Sly",
  "Smirking",
  "Spinning",
  "Spirited",
  "Strange",
  "Striped",
  "Swag",
  "Thirsty",
  "Tilted",
  "Tin",
  "Tipsy",
  "Turquoise",
  "Twirling",
  "Twisted",
  "Velvet",
  "Wandering",
  "Whistling",
  "Wild",
  "Wily",
  "Wired",
  "Wise",
  "Wiz",
];

const subjects = [
  "Anchor",
  "Angel",
  "Arrow",
  "Barman",
  "Baron",
  "Barrel",
  "Barrens",
  "Bear",
  "Beaver",
  "Biz",
  "Bootlegger",
  "Bottle",
  "Breeder",
  "Brew",
  "Bull",
  "Cat",
  "Chip Truth",
  "Cleaner",
  "Clip",
  "Cloud",
  "Cow",
  "Crown",
  "Cup",
  "Dataslave",
  "Deck",
  "Decker",
  "Deckhead",
  "Dog",
  "Dragon",
  "Elixir",
  "Escape",
  "Fetishman",
  "Fish",
  "Flask",
  "Fox",
  "Glass",
  "Go-Gang",
  "Go-Go-Go",
  "Growler",
  "Hacker",
  "Heatwave",
  "Hedgehog",
  "Horse",
  "Hour",
  "Jackroller",
  "Jester",
  "Jewel",
  "Johnson",
  "Keg",
  "Lady",
  "Lion",
  "Lizard",
  "Martini",
  "Minx",
  "Moose",
  "Nightcap",
  "Nomad",
  "Nuyen",
  "Omae",
  "Outlaw",
  "Palm",
  "Panzer",
  "Paydata",
  "Pig",
  "Pint",
  "Pour",
  "Rabbit",
  "Razorgirl",
  "Razorguy",
  "Root",
  "Sage",
  "Sailor",
  "Samurai",
  "Screamer",
  "Shot",
  "Sidecar",
  "Sip",
  "Squirrel",
  "Stone",
  "Stout",
  "Street",
  "Suit",
  "T-Bird",
  "Table",
  "Tap",
  "Tiger",
  "Time",
  "Traveler",
  "Vibes",
  "Wagemage",
  "Wageslave",
  "Wagon",
  "Wingman",
  "Wizard",
];

const businesses = [
  "Speakeasy",
  "Taproom",
  "Spot",
  "Saloon",
  "Roadhouse",
  "Parlor",
  "Pub",
  "Outpost",
  "Hideout",
  "Lounge",
  "Bar and Grille",
  "Garage",
  "Emporium",
  "Eatery",
  "Brewpub",
  "Club",
  "Brewhouse",
  "Bistro",
  "Bar and Grill",
  "Bar",
  "Ale House",
];

const descriptorIncrement = 1 / descriptors.length;
const subjectIncrement = 1 / subjects.length;
const businessIncrement = 1 / businesses.length;

const descriptorValues = Array.from(
  { length: descriptors.length },
  (_v, i) => i * descriptorIncrement
);

const subjectValues = Array.from(
  { length: subjects.length },
  (_v, i) => i * subjectIncrement
);

const businessValues = Array.from(
  { length: businesses.length },
  (_v, i) => i * businessIncrement
);

export const barName = () => {
  const descriptorThreshold = Math.random();
  const subjectThreshold = Math.random();
  const businessThreshold = Math.random();

  const descriptorIndex = descriptorValues.indexOf(
    descriptorValues
      .filter((val: number) => val < descriptorThreshold)
      .reverse()[0]
  );

  const subjectIndex = subjectValues.indexOf(
    subjectValues.filter((val: number) => val < subjectThreshold).reverse()[0]
  );

  const businessIndex = businessValues.indexOf(
    businessValues.filter((val: number) => val < businessThreshold).reverse()[0]
  );

  return `${descriptors[descriptorIndex]} ${subjects[subjectIndex]} ${businesses[businessIndex]}`;
};
