import { randomValue } from "@/utils/random-value";

const hosts = [
  "BioBotic",
  "BioN",
  "Biometrix",
  "BionicPort",
  "Bioxx",
  "Buzztrix",
  "ChipCycle",
  "Chipline",
  "Chiprific",
  "Commer",
  "Cryptoid",
  "CyberCryptic",
  "CyberCubicle",
  "Cyberum",
  "Cybotics",
  "Databump",
  "DigiCC",
  "DynaCircuit",
  "Geektrix",
  "Hyperzo",
  "Intersocket",
  "Magiccube",
  "Magicker",
  "Magicon",
  "Metable",
  "MiliDex",
  "NMatrix",
  "Nerdork",
  "Neucafe",
  "NeuroPond",
  "Neuromic",
  "Pushbyte",
  "QTech",
  "QuantumBotics",
  "RipGuard",
  "RunMagic",
  "Tapscrypt",
  "Techbrain",
  "WizForce",
];

export const matrixHostName = () => randomValue(hosts);
