import { randomValue } from "@/utils/random-value";

const neighborhoods = [
  "Arakura",
  "Ashitake",
  "Bad Axe",
  "Bellwood",
  "Benavides",
  "Campechana",
  "Chikuni",
  "Dongshen",
  "Easley",
  "Fujisawa",
  "Fukase",
  "Garnett",
  "Hantan",
  "Hettick",
  "Hotei",
  "Hushan",
  "Kawamata",
  "Keshi",
  "Kunigami",
  "La Grande",
  "Lafayette",
  "Laguna",
  "Laughlin",
  "Locos",
  "Long Neck",
  "Macachi",
  "Mashi",
  "Nason",
  "Obert",
  "Ortiga",
  "Osborne",
  "Pote",
  "Qingshi",
  "Ranburne",
  "Rembrandt",
  "Rockwell",
  "Shikama",
  "Temanche",
  "Tigre",
  "Tila",
  "Tsumasaki",
  "Urakawa",
  "Varnell",
  "Virulento",
  "Walden",
  "Weston",
  "Wu-te",
  "Yeh-ho-chan",
  "Yuantou",
  "Zhaoyan",
];

const locations = ["Barrens", "Slums", "Squat"];

export const urbanHellHole = () =>
  `${randomValue(neighborhoods)} ${randomValue(locations)}`;
